export const screens = {
  SPLASH: 'Splash',
  AUTH: 'SignedOutNavigator',
  MAIN: 'SignedInNavigator',
  LOGIN: 'Login',
  DRAWER: 'DrawerNavigator',
  VEHICLES: 'Vehicles',
  VEHICLE_DETAILS: 'Vehicle Details',
  DRIVERS: 'Drivers',
  DRIVER_DETAILS: 'Driver Details',
  TRANSPORT: 'Transport',
  MAIN_DRIVER: 'SignedInDriverNavigator',
  REPORTS: 'Reports',
  REPORT_DETAILS: 'Report Details',
  CONFIGURED_REPORT_DETAILS: 'Configured Report Details',
};
